// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beans/BeanCommonMessage.proto

package com.ninelook.wecard.protocol.beans;

public final class BeanCommonMessage {
  private BeanCommonMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ItemByIntIntOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 key = 1;
    /**
     * <code>required int32 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required int32 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    int getKey();

    // required int32 value = 2;
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code ItemByIntInt}
   *
   * <pre>
   *Item - Integer:Integer
   * </pre>
   */
  public static final class ItemByIntInt extends
      com.google.protobuf.GeneratedMessage
      implements ItemByIntIntOrBuilder {
    // Use ItemByIntInt.newBuilder() to construct.
    private ItemByIntInt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemByIntInt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemByIntInt defaultInstance;
    public static ItemByIntInt getDefaultInstance() {
      return defaultInstance;
    }

    public ItemByIntInt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemByIntInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              key_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByIntInt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByIntInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.class, com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemByIntInt> PARSER =
        new com.google.protobuf.AbstractParser<ItemByIntInt>() {
      public ItemByIntInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemByIntInt(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemByIntInt> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private int key_;
    /**
     * <code>required int32 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    public int getKey() {
      return key_;
    }

    // required int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      key_ = 0;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemByIntInt}
     *
     * <pre>
     *Item - Integer:Integer
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByIntInt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByIntInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.class, com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.Builder.class);
      }

      // Construct using com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByIntInt_descriptor;
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt getDefaultInstanceForType() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.getDefaultInstance();
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt build() {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt buildPartial() {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt result = new com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt) {
          return mergeFrom((com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt other) {
        if (other == com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByIntInt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 key = 1;
      private int key_ ;
      /**
       * <code>required int32 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public int getKey() {
        return key_;
      }
      /**
       * <code>required int32 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public Builder setKey(int value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0;
        onChanged();
        return this;
      }

      // required int32 value = 2;
      private int value_ ;
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemByIntInt)
    }

    static {
      defaultInstance = new ItemByIntInt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemByIntInt)
  }

  public interface ItemByLongIntOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int64 key = 1;
    /**
     * <code>required int64 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    boolean hasKey();
    /**
     * <code>required int64 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    long getKey();

    // required int32 value = 2;
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    boolean hasValue();
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code ItemByLongInt}
   *
   * <pre>
   *Item - Long:Integer
   * </pre>
   */
  public static final class ItemByLongInt extends
      com.google.protobuf.GeneratedMessage
      implements ItemByLongIntOrBuilder {
    // Use ItemByLongInt.newBuilder() to construct.
    private ItemByLongInt(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ItemByLongInt(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ItemByLongInt defaultInstance;
    public static ItemByLongInt getDefaultInstance() {
      return defaultInstance;
    }

    public ItemByLongInt getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ItemByLongInt(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              key_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByLongInt_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByLongInt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.class, com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.Builder.class);
    }

    public static com.google.protobuf.Parser<ItemByLongInt> PARSER =
        new com.google.protobuf.AbstractParser<ItemByLongInt>() {
      public ItemByLongInt parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ItemByLongInt(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ItemByLongInt> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int64 key = 1;
    public static final int KEY_FIELD_NUMBER = 1;
    private long key_;
    /**
     * <code>required int64 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 key = 1;</code>
     *
     * <pre>
     *key
     * </pre>
     */
    public long getKey() {
      return key_;
    }

    // required int32 value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private int value_;
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 value = 2;</code>
     *
     * <pre>
     *value
     * </pre>
     */
    public int getValue() {
      return value_;
    }

    private void initFields() {
      key_ = 0L;
      value_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasValue()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, key_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ItemByLongInt}
     *
     * <pre>
     *Item - Long:Integer
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongIntOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByLongInt_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByLongInt_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.class, com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.Builder.class);
      }

      // Construct using com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        key_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.internal_static_ItemByLongInt_descriptor;
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt getDefaultInstanceForType() {
        return com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.getDefaultInstance();
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt build() {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt buildPartial() {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt result = new com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.key_ = key_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt) {
          return mergeFrom((com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt other) {
        if (other == com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt.getDefaultInstance()) return this;
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasKey()) {
          
          return false;
        }
        if (!hasValue()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ninelook.wecard.protocol.beans.BeanCommonMessage.ItemByLongInt) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int64 key = 1;
      private long key_ ;
      /**
       * <code>required int64 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public long getKey() {
        return key_;
      }
      /**
       * <code>required int64 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public Builder setKey(long value) {
        bitField0_ |= 0x00000001;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 key = 1;</code>
       *
       * <pre>
       *key
       * </pre>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000001);
        key_ = 0L;
        onChanged();
        return this;
      }

      // required int32 value = 2;
      private int value_ ;
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public Builder setValue(int value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 value = 2;</code>
       *
       * <pre>
       *value
       * </pre>
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ItemByLongInt)
    }

    static {
      defaultInstance = new ItemByLongInt(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ItemByLongInt)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemByIntInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemByIntInt_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ItemByLongInt_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ItemByLongInt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035beans/BeanCommonMessage.proto\"*\n\014ItemB" +
      "yIntInt\022\013\n\003key\030\001 \002(\005\022\r\n\005value\030\002 \002(\005\"+\n\rI" +
      "temByLongInt\022\013\n\003key\030\001 \002(\003\022\r\n\005value\030\002 \002(\005" +
      "B\"\n com.ninelook.wecard.protocol.beans"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ItemByIntInt_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ItemByIntInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemByIntInt_descriptor,
              new java.lang.String[] { "Key", "Value", });
          internal_static_ItemByLongInt_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ItemByLongInt_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ItemByLongInt_descriptor,
              new java.lang.String[] { "Key", "Value", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
