// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beans/BeanBuildMessage.proto

package com.ninelook.wecard.protocol.beans;

public final class BeanBuildMessage {
  private BeanBuildMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BuildInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BuildInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 eid = 1;</code>
     *
     * <pre>
     *唯一ID
     * </pre>
     */
    boolean hasEid();
    /**
     * <code>required int32 eid = 1;</code>
     *
     * <pre>
     *唯一ID
     * </pre>
     */
    int getEid();

    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    int getType();

    /**
     * <code>required int32 serverId = 3;</code>
     *
     * <pre>
     *serverId
     * </pre>
     */
    boolean hasServerId();
    /**
     * <code>required int32 serverId = 3;</code>
     *
     * <pre>
     *serverId
     * </pre>
     */
    int getServerId();

    /**
     * <code>required int32 camp = 4;</code>
     *
     * <pre>
     *所属阵型
     * </pre>
     */
    boolean hasCamp();
    /**
     * <code>required int32 camp = 4;</code>
     *
     * <pre>
     *所属阵型
     * </pre>
     */
    int getCamp();

    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    boolean hasLevel();
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    int getLevel();

    /**
     * <code>required int32 skillId = 6;</code>
     *
     * <pre>
     *技能ID
     * </pre>
     */
    boolean hasSkillId();
    /**
     * <code>required int32 skillId = 6;</code>
     *
     * <pre>
     *技能ID
     * </pre>
     */
    int getSkillId();

    /**
     * <code>required int32 blood = 7;</code>
     *
     * <pre>
     *血量
     * </pre>
     */
    boolean hasBlood();
    /**
     * <code>required int32 blood = 7;</code>
     *
     * <pre>
     *血量
     * </pre>
     */
    int getBlood();

    /**
     * <code>required int32 attackNum = 8;</code>
     *
     * <pre>
     *攻击力
     * </pre>
     */
    boolean hasAttackNum();
    /**
     * <code>required int32 attackNum = 8;</code>
     *
     * <pre>
     *攻击力
     * </pre>
     */
    int getAttackNum();

    /**
     * <code>required int32 defenceNum = 9;</code>
     *
     * <pre>
     *防御力
     * </pre>
     */
    boolean hasDefenceNum();
    /**
     * <code>required int32 defenceNum = 9;</code>
     *
     * <pre>
     *防御力
     * </pre>
     */
    int getDefenceNum();

    /**
     * <code>required int32 magicAttackNum = 10;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    boolean hasMagicAttackNum();
    /**
     * <code>required int32 magicAttackNum = 10;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    int getMagicAttackNum();

    /**
     * <code>required int32 magicDefense = 11;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    boolean hasMagicDefense();
    /**
     * <code>required int32 magicDefense = 11;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    int getMagicDefense();

    /**
     * <code>required float speed = 12;</code>
     *
     * <pre>
     *移动速度
     * </pre>
     */
    boolean hasSpeed();
    /**
     * <code>required float speed = 12;</code>
     *
     * <pre>
     *移动速度
     * </pre>
     */
    float getSpeed();

    /**
     * <code>required int32 x = 13;</code>
     *
     * <pre>
     *X轴
     * </pre>
     */
    boolean hasX();
    /**
     * <code>required int32 x = 13;</code>
     *
     * <pre>
     *X轴
     * </pre>
     */
    int getX();
  }
  /**
   * Protobuf type {@code BuildInfo}
   *
   * <pre>
   *build信息
   * </pre>
   */
  public static final class BuildInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:BuildInfo)
      BuildInfoOrBuilder {
    // Use BuildInfo.newBuilder() to construct.
    private BuildInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BuildInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BuildInfo defaultInstance;
    public static BuildInfo getDefaultInstance() {
      return defaultInstance;
    }

    public BuildInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BuildInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              eid_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              type_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              serverId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              camp_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              level_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              skillId_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              blood_ = input.readInt32();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              attackNum_ = input.readInt32();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              defenceNum_ = input.readInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000200;
              magicAttackNum_ = input.readInt32();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              magicDefense_ = input.readInt32();
              break;
            }
            case 101: {
              bitField0_ |= 0x00000800;
              speed_ = input.readFloat();
              break;
            }
            case 104: {
              bitField0_ |= 0x00001000;
              x_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ninelook.wecard.protocol.beans.BeanBuildMessage.internal_static_BuildInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ninelook.wecard.protocol.beans.BeanBuildMessage.internal_static_BuildInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.class, com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<BuildInfo> PARSER =
        new com.google.protobuf.AbstractParser<BuildInfo>() {
      public BuildInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BuildInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BuildInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EID_FIELD_NUMBER = 1;
    private int eid_;
    /**
     * <code>required int32 eid = 1;</code>
     *
     * <pre>
     *唯一ID
     * </pre>
     */
    public boolean hasEid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 eid = 1;</code>
     *
     * <pre>
     *唯一ID
     * </pre>
     */
    public int getEid() {
      return eid_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 type = 2;</code>
     *
     * <pre>
     *类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    public static final int SERVERID_FIELD_NUMBER = 3;
    private int serverId_;
    /**
     * <code>required int32 serverId = 3;</code>
     *
     * <pre>
     *serverId
     * </pre>
     */
    public boolean hasServerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 serverId = 3;</code>
     *
     * <pre>
     *serverId
     * </pre>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int CAMP_FIELD_NUMBER = 4;
    private int camp_;
    /**
     * <code>required int32 camp = 4;</code>
     *
     * <pre>
     *所属阵型
     * </pre>
     */
    public boolean hasCamp() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 camp = 4;</code>
     *
     * <pre>
     *所属阵型
     * </pre>
     */
    public int getCamp() {
      return camp_;
    }

    public static final int LEVEL_FIELD_NUMBER = 5;
    private int level_;
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required int32 level = 5;</code>
     *
     * <pre>
     *等级
     * </pre>
     */
    public int getLevel() {
      return level_;
    }

    public static final int SKILLID_FIELD_NUMBER = 6;
    private int skillId_;
    /**
     * <code>required int32 skillId = 6;</code>
     *
     * <pre>
     *技能ID
     * </pre>
     */
    public boolean hasSkillId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required int32 skillId = 6;</code>
     *
     * <pre>
     *技能ID
     * </pre>
     */
    public int getSkillId() {
      return skillId_;
    }

    public static final int BLOOD_FIELD_NUMBER = 7;
    private int blood_;
    /**
     * <code>required int32 blood = 7;</code>
     *
     * <pre>
     *血量
     * </pre>
     */
    public boolean hasBlood() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>required int32 blood = 7;</code>
     *
     * <pre>
     *血量
     * </pre>
     */
    public int getBlood() {
      return blood_;
    }

    public static final int ATTACKNUM_FIELD_NUMBER = 8;
    private int attackNum_;
    /**
     * <code>required int32 attackNum = 8;</code>
     *
     * <pre>
     *攻击力
     * </pre>
     */
    public boolean hasAttackNum() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>required int32 attackNum = 8;</code>
     *
     * <pre>
     *攻击力
     * </pre>
     */
    public int getAttackNum() {
      return attackNum_;
    }

    public static final int DEFENCENUM_FIELD_NUMBER = 9;
    private int defenceNum_;
    /**
     * <code>required int32 defenceNum = 9;</code>
     *
     * <pre>
     *防御力
     * </pre>
     */
    public boolean hasDefenceNum() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required int32 defenceNum = 9;</code>
     *
     * <pre>
     *防御力
     * </pre>
     */
    public int getDefenceNum() {
      return defenceNum_;
    }

    public static final int MAGICATTACKNUM_FIELD_NUMBER = 10;
    private int magicAttackNum_;
    /**
     * <code>required int32 magicAttackNum = 10;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    public boolean hasMagicAttackNum() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>required int32 magicAttackNum = 10;</code>
     *
     * <pre>
     *魔法攻击力
     * </pre>
     */
    public int getMagicAttackNum() {
      return magicAttackNum_;
    }

    public static final int MAGICDEFENSE_FIELD_NUMBER = 11;
    private int magicDefense_;
    /**
     * <code>required int32 magicDefense = 11;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    public boolean hasMagicDefense() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>required int32 magicDefense = 11;</code>
     *
     * <pre>
     *魔法防御力
     * </pre>
     */
    public int getMagicDefense() {
      return magicDefense_;
    }

    public static final int SPEED_FIELD_NUMBER = 12;
    private float speed_;
    /**
     * <code>required float speed = 12;</code>
     *
     * <pre>
     *移动速度
     * </pre>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000800) == 0x00000800);
    }
    /**
     * <code>required float speed = 12;</code>
     *
     * <pre>
     *移动速度
     * </pre>
     */
    public float getSpeed() {
      return speed_;
    }

    public static final int X_FIELD_NUMBER = 13;
    private int x_;
    /**
     * <code>required int32 x = 13;</code>
     *
     * <pre>
     *X轴
     * </pre>
     */
    public boolean hasX() {
      return ((bitField0_ & 0x00001000) == 0x00001000);
    }
    /**
     * <code>required int32 x = 13;</code>
     *
     * <pre>
     *X轴
     * </pre>
     */
    public int getX() {
      return x_;
    }

    private void initFields() {
      eid_ = 0;
      type_ = 0;
      serverId_ = 0;
      camp_ = 0;
      level_ = 0;
      skillId_ = 0;
      blood_ = 0;
      attackNum_ = 0;
      defenceNum_ = 0;
      magicAttackNum_ = 0;
      magicDefense_ = 0;
      speed_ = 0F;
      x_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasServerId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSkillId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBlood()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAttackNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDefenceNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagicAttackNum()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagicDefense()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, eid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, camp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, skillId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(7, blood_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt32(8, attackNum_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeInt32(9, defenceNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeInt32(10, magicAttackNum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeInt32(11, magicDefense_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        output.writeFloat(12, speed_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        output.writeInt32(13, x_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, eid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, type_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serverId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, camp_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, level_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, skillId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, blood_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, attackNum_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(9, defenceNum_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(10, magicAttackNum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, magicDefense_);
      }
      if (((bitField0_ & 0x00000800) == 0x00000800)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(12, speed_);
      }
      if (((bitField0_ & 0x00001000) == 0x00001000)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, x_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BuildInfo}
     *
     * <pre>
     *build信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BuildInfo)
        com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ninelook.wecard.protocol.beans.BeanBuildMessage.internal_static_BuildInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ninelook.wecard.protocol.beans.BeanBuildMessage.internal_static_BuildInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.class, com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.Builder.class);
      }

      // Construct using com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        camp_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        level_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        skillId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        blood_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        attackNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000080);
        defenceNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        magicAttackNum_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        magicDefense_ = 0;
        bitField0_ = (bitField0_ & ~0x00000400);
        speed_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000800);
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00001000);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ninelook.wecard.protocol.beans.BeanBuildMessage.internal_static_BuildInfo_descriptor;
      }

      public com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo getDefaultInstanceForType() {
        return com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.getDefaultInstance();
      }

      public com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo build() {
        com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo buildPartial() {
        com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo result = new com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eid_ = eid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.serverId_ = serverId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.camp_ = camp_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.skillId_ = skillId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.blood_ = blood_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.attackNum_ = attackNum_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.defenceNum_ = defenceNum_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.magicAttackNum_ = magicAttackNum_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.magicDefense_ = magicDefense_;
        if (((from_bitField0_ & 0x00000800) == 0x00000800)) {
          to_bitField0_ |= 0x00000800;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00001000) == 0x00001000)) {
          to_bitField0_ |= 0x00001000;
        }
        result.x_ = x_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo) {
          return mergeFrom((com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo other) {
        if (other == com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo.getDefaultInstance()) return this;
        if (other.hasEid()) {
          setEid(other.getEid());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasServerId()) {
          setServerId(other.getServerId());
        }
        if (other.hasCamp()) {
          setCamp(other.getCamp());
        }
        if (other.hasLevel()) {
          setLevel(other.getLevel());
        }
        if (other.hasSkillId()) {
          setSkillId(other.getSkillId());
        }
        if (other.hasBlood()) {
          setBlood(other.getBlood());
        }
        if (other.hasAttackNum()) {
          setAttackNum(other.getAttackNum());
        }
        if (other.hasDefenceNum()) {
          setDefenceNum(other.getDefenceNum());
        }
        if (other.hasMagicAttackNum()) {
          setMagicAttackNum(other.getMagicAttackNum());
        }
        if (other.hasMagicDefense()) {
          setMagicDefense(other.getMagicDefense());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasX()) {
          setX(other.getX());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEid()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!hasServerId()) {
          
          return false;
        }
        if (!hasCamp()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasSkillId()) {
          
          return false;
        }
        if (!hasBlood()) {
          
          return false;
        }
        if (!hasAttackNum()) {
          
          return false;
        }
        if (!hasDefenceNum()) {
          
          return false;
        }
        if (!hasMagicAttackNum()) {
          
          return false;
        }
        if (!hasMagicDefense()) {
          
          return false;
        }
        if (!hasSpeed()) {
          
          return false;
        }
        if (!hasX()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ninelook.wecard.protocol.beans.BeanBuildMessage.BuildInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int eid_ ;
      /**
       * <code>required int32 eid = 1;</code>
       *
       * <pre>
       *唯一ID
       * </pre>
       */
      public boolean hasEid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 eid = 1;</code>
       *
       * <pre>
       *唯一ID
       * </pre>
       */
      public int getEid() {
        return eid_;
      }
      /**
       * <code>required int32 eid = 1;</code>
       *
       * <pre>
       *唯一ID
       * </pre>
       */
      public Builder setEid(int value) {
        bitField0_ |= 0x00000001;
        eid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 eid = 1;</code>
       *
       * <pre>
       *唯一ID
       * </pre>
       */
      public Builder clearEid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eid_ = 0;
        onChanged();
        return this;
      }

      private int type_ ;
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000002;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 2;</code>
       *
       * <pre>
       *类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>required int32 serverId = 3;</code>
       *
       * <pre>
       *serverId
       * </pre>
       */
      public boolean hasServerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 serverId = 3;</code>
       *
       * <pre>
       *serverId
       * </pre>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>required int32 serverId = 3;</code>
       *
       * <pre>
       *serverId
       * </pre>
       */
      public Builder setServerId(int value) {
        bitField0_ |= 0x00000004;
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 serverId = 3;</code>
       *
       * <pre>
       *serverId
       * </pre>
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private int camp_ ;
      /**
       * <code>required int32 camp = 4;</code>
       *
       * <pre>
       *所属阵型
       * </pre>
       */
      public boolean hasCamp() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 camp = 4;</code>
       *
       * <pre>
       *所属阵型
       * </pre>
       */
      public int getCamp() {
        return camp_;
      }
      /**
       * <code>required int32 camp = 4;</code>
       *
       * <pre>
       *所属阵型
       * </pre>
       */
      public Builder setCamp(int value) {
        bitField0_ |= 0x00000008;
        camp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 camp = 4;</code>
       *
       * <pre>
       *所属阵型
       * </pre>
       */
      public Builder clearCamp() {
        bitField0_ = (bitField0_ & ~0x00000008);
        camp_ = 0;
        onChanged();
        return this;
      }

      private int level_ ;
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder setLevel(int value) {
        bitField0_ |= 0x00000010;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 level = 5;</code>
       *
       * <pre>
       *等级
       * </pre>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000010);
        level_ = 0;
        onChanged();
        return this;
      }

      private int skillId_ ;
      /**
       * <code>required int32 skillId = 6;</code>
       *
       * <pre>
       *技能ID
       * </pre>
       */
      public boolean hasSkillId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required int32 skillId = 6;</code>
       *
       * <pre>
       *技能ID
       * </pre>
       */
      public int getSkillId() {
        return skillId_;
      }
      /**
       * <code>required int32 skillId = 6;</code>
       *
       * <pre>
       *技能ID
       * </pre>
       */
      public Builder setSkillId(int value) {
        bitField0_ |= 0x00000020;
        skillId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 skillId = 6;</code>
       *
       * <pre>
       *技能ID
       * </pre>
       */
      public Builder clearSkillId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        skillId_ = 0;
        onChanged();
        return this;
      }

      private int blood_ ;
      /**
       * <code>required int32 blood = 7;</code>
       *
       * <pre>
       *血量
       * </pre>
       */
      public boolean hasBlood() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>required int32 blood = 7;</code>
       *
       * <pre>
       *血量
       * </pre>
       */
      public int getBlood() {
        return blood_;
      }
      /**
       * <code>required int32 blood = 7;</code>
       *
       * <pre>
       *血量
       * </pre>
       */
      public Builder setBlood(int value) {
        bitField0_ |= 0x00000040;
        blood_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 blood = 7;</code>
       *
       * <pre>
       *血量
       * </pre>
       */
      public Builder clearBlood() {
        bitField0_ = (bitField0_ & ~0x00000040);
        blood_ = 0;
        onChanged();
        return this;
      }

      private int attackNum_ ;
      /**
       * <code>required int32 attackNum = 8;</code>
       *
       * <pre>
       *攻击力
       * </pre>
       */
      public boolean hasAttackNum() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>required int32 attackNum = 8;</code>
       *
       * <pre>
       *攻击力
       * </pre>
       */
      public int getAttackNum() {
        return attackNum_;
      }
      /**
       * <code>required int32 attackNum = 8;</code>
       *
       * <pre>
       *攻击力
       * </pre>
       */
      public Builder setAttackNum(int value) {
        bitField0_ |= 0x00000080;
        attackNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 attackNum = 8;</code>
       *
       * <pre>
       *攻击力
       * </pre>
       */
      public Builder clearAttackNum() {
        bitField0_ = (bitField0_ & ~0x00000080);
        attackNum_ = 0;
        onChanged();
        return this;
      }

      private int defenceNum_ ;
      /**
       * <code>required int32 defenceNum = 9;</code>
       *
       * <pre>
       *防御力
       * </pre>
       */
      public boolean hasDefenceNum() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required int32 defenceNum = 9;</code>
       *
       * <pre>
       *防御力
       * </pre>
       */
      public int getDefenceNum() {
        return defenceNum_;
      }
      /**
       * <code>required int32 defenceNum = 9;</code>
       *
       * <pre>
       *防御力
       * </pre>
       */
      public Builder setDefenceNum(int value) {
        bitField0_ |= 0x00000100;
        defenceNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 defenceNum = 9;</code>
       *
       * <pre>
       *防御力
       * </pre>
       */
      public Builder clearDefenceNum() {
        bitField0_ = (bitField0_ & ~0x00000100);
        defenceNum_ = 0;
        onChanged();
        return this;
      }

      private int magicAttackNum_ ;
      /**
       * <code>required int32 magicAttackNum = 10;</code>
       *
       * <pre>
       *魔法攻击力
       * </pre>
       */
      public boolean hasMagicAttackNum() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>required int32 magicAttackNum = 10;</code>
       *
       * <pre>
       *魔法攻击力
       * </pre>
       */
      public int getMagicAttackNum() {
        return magicAttackNum_;
      }
      /**
       * <code>required int32 magicAttackNum = 10;</code>
       *
       * <pre>
       *魔法攻击力
       * </pre>
       */
      public Builder setMagicAttackNum(int value) {
        bitField0_ |= 0x00000200;
        magicAttackNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 magicAttackNum = 10;</code>
       *
       * <pre>
       *魔法攻击力
       * </pre>
       */
      public Builder clearMagicAttackNum() {
        bitField0_ = (bitField0_ & ~0x00000200);
        magicAttackNum_ = 0;
        onChanged();
        return this;
      }

      private int magicDefense_ ;
      /**
       * <code>required int32 magicDefense = 11;</code>
       *
       * <pre>
       *魔法防御力
       * </pre>
       */
      public boolean hasMagicDefense() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>required int32 magicDefense = 11;</code>
       *
       * <pre>
       *魔法防御力
       * </pre>
       */
      public int getMagicDefense() {
        return magicDefense_;
      }
      /**
       * <code>required int32 magicDefense = 11;</code>
       *
       * <pre>
       *魔法防御力
       * </pre>
       */
      public Builder setMagicDefense(int value) {
        bitField0_ |= 0x00000400;
        magicDefense_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 magicDefense = 11;</code>
       *
       * <pre>
       *魔法防御力
       * </pre>
       */
      public Builder clearMagicDefense() {
        bitField0_ = (bitField0_ & ~0x00000400);
        magicDefense_ = 0;
        onChanged();
        return this;
      }

      private float speed_ ;
      /**
       * <code>required float speed = 12;</code>
       *
       * <pre>
       *移动速度
       * </pre>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000800) == 0x00000800);
      }
      /**
       * <code>required float speed = 12;</code>
       *
       * <pre>
       *移动速度
       * </pre>
       */
      public float getSpeed() {
        return speed_;
      }
      /**
       * <code>required float speed = 12;</code>
       *
       * <pre>
       *移动速度
       * </pre>
       */
      public Builder setSpeed(float value) {
        bitField0_ |= 0x00000800;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float speed = 12;</code>
       *
       * <pre>
       *移动速度
       * </pre>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000800);
        speed_ = 0F;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>required int32 x = 13;</code>
       *
       * <pre>
       *X轴
       * </pre>
       */
      public boolean hasX() {
        return ((bitField0_ & 0x00001000) == 0x00001000);
      }
      /**
       * <code>required int32 x = 13;</code>
       *
       * <pre>
       *X轴
       * </pre>
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>required int32 x = 13;</code>
       *
       * <pre>
       *X轴
       * </pre>
       */
      public Builder setX(int value) {
        bitField0_ |= 0x00001000;
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 x = 13;</code>
       *
       * <pre>
       *X轴
       * </pre>
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00001000);
        x_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BuildInfo)
    }

    static {
      defaultInstance = new BuildInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BuildInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BuildInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BuildInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034beans/BeanBuildMessage.proto\032\034beans/Be" +
      "anSceneMessage.proto\"\344\001\n\tBuildInfo\022\013\n\003ei" +
      "d\030\001 \002(\005\022\014\n\004type\030\002 \002(\005\022\020\n\010serverId\030\003 \002(\005\022" +
      "\014\n\004camp\030\004 \002(\005\022\r\n\005level\030\005 \002(\005\022\017\n\007skillId\030" +
      "\006 \002(\005\022\r\n\005blood\030\007 \002(\005\022\021\n\tattackNum\030\010 \002(\005\022" +
      "\022\n\ndefenceNum\030\t \002(\005\022\026\n\016magicAttackNum\030\n " +
      "\002(\005\022\024\n\014magicDefense\030\013 \002(\005\022\r\n\005speed\030\014 \002(\002" +
      "\022\t\n\001x\030\r \002(\005B$\n\"com.ninelook.wecard.proto" +
      "col.beans"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor(),
        }, assigner);
    internal_static_BuildInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BuildInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_BuildInfo_descriptor,
        new java.lang.String[] { "Eid", "Type", "ServerId", "Camp", "Level", "SkillId", "Blood", "AttackNum", "DefenceNum", "MagicAttackNum", "MagicDefense", "Speed", "X", });
    com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
