// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/ApiHeroMessage.proto

package com.ninelook.wecard.protocol.apis;

public final class ApiHeroMessage {
  private ApiHeroMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SReqHeroMoveOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SReqHeroMove)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    boolean hasHeroPosInfo();
    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo getHeroPosInfo();
    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder getHeroPosInfoOrBuilder();
  }
  /**
   * Protobuf type {@code SReqHeroMove}
   *
   * <pre>
   *英雄移动
   * </pre>
   */
  public static final class SReqHeroMove extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:SReqHeroMove)
      SReqHeroMoveOrBuilder {
    // Use SReqHeroMove.newBuilder() to construct.
    private SReqHeroMove(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SReqHeroMove(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SReqHeroMove defaultInstance;
    public static SReqHeroMove getDefaultInstance() {
      return defaultInstance;
    }

    public SReqHeroMove getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SReqHeroMove(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = heroPosInfo_.toBuilder();
              }
              heroPosInfo_ = input.readMessage(com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(heroPosInfo_);
                heroPosInfo_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ninelook.wecard.protocol.apis.ApiHeroMessage.internal_static_SReqHeroMove_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ninelook.wecard.protocol.apis.ApiHeroMessage.internal_static_SReqHeroMove_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.class, com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.Builder.class);
    }

    public static com.google.protobuf.Parser<SReqHeroMove> PARSER =
        new com.google.protobuf.AbstractParser<SReqHeroMove>() {
      public SReqHeroMove parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SReqHeroMove(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SReqHeroMove> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int HEROPOSINFO_FIELD_NUMBER = 1;
    private com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo heroPosInfo_;
    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    public boolean hasHeroPosInfo() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    public com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo getHeroPosInfo() {
      return heroPosInfo_;
    }
    /**
     * <code>required .PosInfo heroPosInfo = 1;</code>
     *
     * <pre>
     *英雄移动信息
     * </pre>
     */
    public com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder getHeroPosInfoOrBuilder() {
      return heroPosInfo_;
    }

    private void initFields() {
      heroPosInfo_ = com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasHeroPosInfo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getHeroPosInfo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, heroPosInfo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, heroPosInfo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SReqHeroMove}
     *
     * <pre>
     *英雄移动
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SReqHeroMove)
        com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ninelook.wecard.protocol.apis.ApiHeroMessage.internal_static_SReqHeroMove_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ninelook.wecard.protocol.apis.ApiHeroMessage.internal_static_SReqHeroMove_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.class, com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.Builder.class);
      }

      // Construct using com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHeroPosInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (heroPosInfoBuilder_ == null) {
          heroPosInfo_ = com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.getDefaultInstance();
        } else {
          heroPosInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ninelook.wecard.protocol.apis.ApiHeroMessage.internal_static_SReqHeroMove_descriptor;
      }

      public com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove getDefaultInstanceForType() {
        return com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.getDefaultInstance();
      }

      public com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove build() {
        com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove buildPartial() {
        com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove result = new com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (heroPosInfoBuilder_ == null) {
          result.heroPosInfo_ = heroPosInfo_;
        } else {
          result.heroPosInfo_ = heroPosInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove) {
          return mergeFrom((com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove other) {
        if (other == com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove.getDefaultInstance()) return this;
        if (other.hasHeroPosInfo()) {
          mergeHeroPosInfo(other.getHeroPosInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasHeroPosInfo()) {
          
          return false;
        }
        if (!getHeroPosInfo().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ninelook.wecard.protocol.apis.ApiHeroMessage.SReqHeroMove) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo heroPosInfo_ = com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder> heroPosInfoBuilder_;
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public boolean hasHeroPosInfo() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo getHeroPosInfo() {
        if (heroPosInfoBuilder_ == null) {
          return heroPosInfo_;
        } else {
          return heroPosInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public Builder setHeroPosInfo(com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo value) {
        if (heroPosInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          heroPosInfo_ = value;
          onChanged();
        } else {
          heroPosInfoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public Builder setHeroPosInfo(
          com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder builderForValue) {
        if (heroPosInfoBuilder_ == null) {
          heroPosInfo_ = builderForValue.build();
          onChanged();
        } else {
          heroPosInfoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public Builder mergeHeroPosInfo(com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo value) {
        if (heroPosInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              heroPosInfo_ != com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.getDefaultInstance()) {
            heroPosInfo_ =
              com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.newBuilder(heroPosInfo_).mergeFrom(value).buildPartial();
          } else {
            heroPosInfo_ = value;
          }
          onChanged();
        } else {
          heroPosInfoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public Builder clearHeroPosInfo() {
        if (heroPosInfoBuilder_ == null) {
          heroPosInfo_ = com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.getDefaultInstance();
          onChanged();
        } else {
          heroPosInfoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder getHeroPosInfoBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getHeroPosInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      public com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder getHeroPosInfoOrBuilder() {
        if (heroPosInfoBuilder_ != null) {
          return heroPosInfoBuilder_.getMessageOrBuilder();
        } else {
          return heroPosInfo_;
        }
      }
      /**
       * <code>required .PosInfo heroPosInfo = 1;</code>
       *
       * <pre>
       *英雄移动信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder> 
          getHeroPosInfoFieldBuilder() {
        if (heroPosInfoBuilder_ == null) {
          heroPosInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfo.Builder, com.ninelook.wecard.protocol.beans.BeanEntityMessage.PosInfoOrBuilder>(
                  getHeroPosInfo(),
                  getParentForChildren(),
                  isClean());
          heroPosInfo_ = null;
        }
        return heroPosInfoBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:SReqHeroMove)
    }

    static {
      defaultInstance = new SReqHeroMove(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:SReqHeroMove)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SReqHeroMove_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_SReqHeroMove_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031apis/ApiHeroMessage.proto\032\034beans/BeanS" +
      "ceneMessage.proto\032\033beans/BeanHomeMessage" +
      ".proto\032\033beans/BeanHeroMessage.proto\032\035bea" +
      "ns/BeanEntityMessage.proto\"-\n\014SReqHeroMo" +
      "ve\022\035\n\013heroPosInfo\030\001 \002(\0132\010.PosInfoB#\n!com" +
      ".ninelook.wecard.protocol.apis"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor(),
          com.ninelook.wecard.protocol.beans.BeanHomeMessage.getDescriptor(),
          com.ninelook.wecard.protocol.beans.BeanHeroMessage.getDescriptor(),
          com.ninelook.wecard.protocol.beans.BeanEntityMessage.getDescriptor(),
        }, assigner);
    internal_static_SReqHeroMove_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SReqHeroMove_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_SReqHeroMove_descriptor,
        new java.lang.String[] { "HeroPosInfo", });
    com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor();
    com.ninelook.wecard.protocol.beans.BeanHomeMessage.getDescriptor();
    com.ninelook.wecard.protocol.beans.BeanHeroMessage.getDescriptor();
    com.ninelook.wecard.protocol.beans.BeanEntityMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
