// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: apis/ApiSceneMessage.proto

package com.ninelook.wecard.protocol.apis;

public final class ApiSceneMessage {
  private ApiSceneMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ReqSceneLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ReqSceneLogin)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code ReqSceneLogin}
   *
   * <pre>
   *登陆接口
   * </pre>
   */
  public static final class ReqSceneLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ReqSceneLogin)
      ReqSceneLoginOrBuilder {
    // Use ReqSceneLogin.newBuilder() to construct.
    private ReqSceneLogin(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ReqSceneLogin(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ReqSceneLogin defaultInstance;
    public static ReqSceneLogin getDefaultInstance() {
      return defaultInstance;
    }

    public ReqSceneLogin getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ReqSceneLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ninelook.wecard.protocol.apis.ApiSceneMessage.internal_static_ReqSceneLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ninelook.wecard.protocol.apis.ApiSceneMessage.internal_static_ReqSceneLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.class, com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.Builder.class);
    }

    public static com.google.protobuf.Parser<ReqSceneLogin> PARSER =
        new com.google.protobuf.AbstractParser<ReqSceneLogin>() {
      public ReqSceneLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ReqSceneLogin(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ReqSceneLogin> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ReqSceneLogin}
     *
     * <pre>
     *登陆接口
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ReqSceneLogin)
        com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.ninelook.wecard.protocol.apis.ApiSceneMessage.internal_static_ReqSceneLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.ninelook.wecard.protocol.apis.ApiSceneMessage.internal_static_ReqSceneLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.class, com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.Builder.class);
      }

      // Construct using com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.ninelook.wecard.protocol.apis.ApiSceneMessage.internal_static_ReqSceneLogin_descriptor;
      }

      public com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin getDefaultInstanceForType() {
        return com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.getDefaultInstance();
      }

      public com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin build() {
        com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin buildPartial() {
        com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin result = new com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin) {
          return mergeFrom((com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin other) {
        if (other == com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.ninelook.wecard.protocol.apis.ApiSceneMessage.ReqSceneLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ReqSceneLogin)
    }

    static {
      defaultInstance = new ReqSceneLogin(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ReqSceneLogin)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReqSceneLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ReqSceneLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032apis/ApiSceneMessage.proto\032\034beans/Bean" +
      "SceneMessage.proto\032\033beans/BeanHomeMessag" +
      "e.proto\"\017\n\rReqSceneLoginB#\n!com.ninelook" +
      ".wecard.protocol.apis"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor(),
          com.ninelook.wecard.protocol.beans.BeanHomeMessage.getDescriptor(),
        }, assigner);
    internal_static_ReqSceneLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ReqSceneLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ReqSceneLogin_descriptor,
        new java.lang.String[] { });
    com.ninelook.wecard.protocol.beans.BeanSceneMessage.getDescriptor();
    com.ninelook.wecard.protocol.beans.BeanHomeMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
